$(document).ready(function(){
  $('#teacher2').hide();
  $('#leader2').hide();
  $('#info').click(function(){
    $('#info2').show(300);
    $('#teacher2').hide(300);
    $('#leader2').hide(300);
  })
  $('#teacher').click(function(){
    $('#info2').hide(300);
    $('#teacher2').show(300);
    $('#leader2').hide(300);
  })
  $('#leader').click(function(){
    $('#info2').hide(300);
    $('#teacher2').hide(300);
    $('#leader2').show(300);
  })
});

